
import pandas as pd
import numpy as np

columns = ['state',
           'county',
           'community',
           'communityname',
           'fold',
           'population',
           'householdsize',
           'racepctblack',
           'racePctWhite',
           'racePctAsian',
           'racePctHisp',
           'agePct12t21',
           'agePct12t29',
           'agePct16t24',
           'agePct65up',
           'numbUrban',
           'pctUrban',
           'medIncome',
           'pctWWage',
           'pctWFarmSelf',
           'pctWInvInc',
           'pctWSocSec',
           'pctWPubAsst',
           'pctWRetire',
           'medFamInc',
           'perCapInc',
           'whitePerCap',
           'blackPerCap',
           'indianPerCap',
           'AsianPerCap',
           'OtherPerCap',
           'HispPerCap',
           'NumUnderPov',
           'PctPopUnderPov',
           'PctLess9thGrade',
           'PctNotHSGrad',
           'PctBSorMore',
           'PctUnemployed',
           'PctEmploy',
           'PctEmplManu',
           'PctEmplProfServ',
           'PctOccupManu',
           'PctOccupMgmtProf',
           'MalePctDivorce',
           'MalePctNevMarr',
           'FemalePctDiv',
           'TotalPctDiv',
           'PersPerFam',
           'PctFam2Par',
           'PctKids2Par',
           'PctYoungKids2Par',
           'PctTeen2Par',
           'PctWorkMomYoungKids',
           'PctWorkMom',
           'NumIlleg',
           'PctIlleg',
           'NumImmig',
           'PctImmigRecent',
           'PctImmigRec5',
           'PctImmigRec8',
           'PctImmigRec10',
           'PctRecentImmig',
           'PctRecImmig5',
           'PctRecImmig8',
           'PctRecImmig10',
           'PctSpeakEnglOnly',
           'PctNotSpeakEnglWell',
           'PctLargHouseFam',
           'PctLargHouseOccup',
           'PersPerOccupHous',
           'PersPerOwnOccHous',
           'PersPerRentOccHous',
           'PctPersOwnOccup',
           'PctPersDenseHous',
           'PctHousLess3BR',
           'MedNumBR',
           'HousVacant',
           'PctHousOccup',
           'PctHousOwnOcc',
           'PctVacantBoarded',
           'PctVacMore6Mos',
           'MedYrHousBuilt',
           'PctHousNoPhone',
           'PctWOFullPlumb',
           'OwnOccLowQuart',
           'OwnOccMedVal',
           'OwnOccHiQuart',
           'RentLowQ',
           'RentMedian',
           'RentHighQ',
           'MedRent',
           'MedRentPctHousInc',
           'MedOwnCostPctInc',
           'MedOwnCostPctIncNoMtg',
           'NumInShelters',
           'NumStreet',
           'PctForeignBorn',
           'PctBornSameState',
           'PctSameHouse85',
           'PctSameCity85',
           'PctSameState85',
           'LemasSwornFT',
           'LemasSwFTPerPop',
           'LemasSwFTFieldOps',
           'LemasSwFTFieldPerPop',
           'LemasTotalReq',
           'LemasTotReqPerPop',
           'PolicReqPerOffic',
           'PolicPerPop',
           'RacialMatchCommPol',
           'PctPolicWhite',
           'PctPolicBlack',
           'PctPolicHisp',
           'PctPolicAsian',
           'PctPolicMinor',
           'OfficAssgnDrugUnits',
           'NumKindsDrugsSeiz',
           'PolicAveOTWorked',
           'LandArea',
           'PopDens',
           'PctUsePubTrans',
           'PolicCars',
           'PolicOperBudg',
           'LemasPctPolicOnPatr',
           'LemasGangUnitDeploy',
           'LemasPctOfficDrugUn',
           'PolicBudgPerPop',
           'ViolentCrimesPerPop']

df = pd.read_csv('../data/communities-crime/communities.data', names=columns, sep=',')
df = df.applymap(lambda x: np.nan if x == '?' else x)

columns_with_nan = list(df.columns[df.isna().any()])
columns_to_remove = columns_with_nan + ['fold']

df = df.drop(columns=columns_to_remove)

prot_words = ['black', 'white', 'asian', 'hisp', 'age']

print(df.head())
print(df.dtypes)
print('HOLA')
print()
